<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EasyWin.Core\EasyWin.Core.csproj" />
    <ProjectReference Include="..\EasyWin.Deployment\EasyWin.Deployment.csproj" />
  </ItemGroup>
</Project>
